name: Build CV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-cv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Just
      uses: taiki-e/install-action@just
      with:
        just-version: 1.36.0

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.10'

    - name: Set up Pandoc
      uses: pandoc/actions/setup@v1

    - name: Set up Tectonic
      uses: wtfjoke/setup-tectonic@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install FontAwesome Free v6
      run: |
        wget https://github.com/FortAwesome/Font-Awesome/releases/download/6.5.2/fontawesome-free-6.5.2-desktop.zip
        sudo unzip -j fontawesome-free-6.5.2-desktop.zip "*/otfs/*" -d /usr/local/share/fonts
        sudo fc-cache -f -v  # Update font cache

    - name: Install Vollkorn, Open Sans, Python packages
      run: |
        just get-fonts
        just pdm-init

    - name: Build PDF with Docker image
      run: |
        just lang=en DOCUMENTS="."

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled CV
        path: ./*.pdf
        compression-level: 0  # it's just a 70kb pdf
