name: Build CV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-cv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Just
      uses: taiki-e/install-action@just
      with:
        just-version: 1.36.0

    - name: Install PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.10'

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-vollkorn fonts-open-sans
        sudo apt-get install -y pandoc texlive-xetex

    - name: Update tlmgr
      run: |
        wget http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
        chmod +x update-tlmgr-latest.sh
        ./update-tlmgr-latest.sh -- --upgrade
        tlmgr init-usertree

    - name: Install Python and XeTeX dependencies
      run: |
        tlmgr install fontawesome5
        just pdm-init

    - name: Build PDF with Docker image
      run: |
        just lang=en DOCUMENTS="."

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Compiled CV
        path: ./*.pdf
